# Generated by Django 2.2.3 on 2019-07-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduapp', '0002_organization_program_semester_subject_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='event')),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Facility')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sayings', models.TextField()),
                ('current_engagement', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='testimonials')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='about_image1',
            field=models.ImageField(default='wsddw', upload_to='organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='about_image2',
            field=models.ImageField(default='asadad', upload_to='organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='certified_teachers',
            field=models.PositiveIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='graduated_students',
            field=models.PositiveIntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='mission_vision',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='years',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
